import { Roboto_Slab } from "next/font/google";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const roboto = Roboto_Slab({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "700"],
});
export default function RootLayout({ children }) {
 return (
   <html lang="en">
     <body className={roboto.className}>{children}</body>
   </html>
 );
}
