import {Roboto_Slab } from 'next/font/google'
import '../globals.css'
import Header from '@/components/Header'

const roboto = Roboto_Slab({ subsets: ["latin"], weight: [ '100' , '200', "300", '400' , "700"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main>
          <Header />

          <div className="p-6 max-w-4xl mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
